/**
 * Vibe Check Quiz — 20 question pool
 * - type: 'fact' (low weight) or 'personality' (high weight)
 * - correct: Devasish’s preference (used for weighted scoring)
 */

export const QUESTION_POOL = [
  // Fact-based (low weight)
  {
    id: 1,
    type: 'fact',
    question: 'My nickname?',
    options: ['Sai ✨', 'Bunny 🐰', 'Lucky 🍀', 'Ghost 👻'],
    correct: 'Sai ✨',
    weight: 3,
  },
  {
    id: 2,
    type: 'fact',
    question: 'My DOB?',
    options: ['June 2 📅', 'May 20 📅', 'July 7 📅', 'Dec 31 📅'],
    correct: 'June 2 📅',
    weight: 3,
  },
  {
    id: 5,
    type: 'fact',
    question: 'How many schools have I studied in?',
    options: ['6 🏫', '3 🏫', '5 🏫', '9 🏫'],
    correct: '6 🏫',
    weight: 4,
  },

  // Personality-based (high weight)
  {
    id: 3,
    type: 'personality',
    question: 'Tea or coffee?',
    options: ['Tea 🍵', 'Coffee ☕'],
    correct: 'Tea 🍵',
    weight: 10,
  },
  {
    id: 4,
    type: 'personality',
    question: 'Italian or Indian food?',
    options: ['Indian food 🍛', 'Italian food 🍝'],
    correct: 'Indian food 🍛',
    weight: 10,
  },
  {
    id: 6,
    type: 'personality',
    question: 'Most liking drink?',
    options: ['Water 💧', 'Mocktail 🍹'],
    correct: 'Water 💧',
    weight: 10,
  },
  {
    id: 7,
    type: 'personality',
    question: 'Dog or cat?',
    options: ['Dog 🐶', 'Cat 🐱'],
    correct: 'Dog 🐶',
    weight: 10,
  },
  {
    id: 8,
    type: 'personality',
    question: 'Favourite Disney character?',
    options: ['Rapunzel 👑', 'Elsa ❄️'],
    correct: 'Rapunzel 👑',
    weight: 10,
  },
  {
    id: 9,
    type: 'personality',
    question: 'Marvel or DC?',
    options: ['Marvel 🦸', 'DC 🦇'],
    correct: 'Marvel 🦸',
    weight: 10,
  },
  {
    id: 10,
    type: 'personality',
    question: 'Favourite hero?',
    options: ['Balayya 🔥', 'Iron Man 🧠'],
    correct: 'Balayya 🔥',
    weight: 10,
  },
  {
    id: 11,
    type: 'personality',
    question: 'Night owl or early bird?',
    options: ['Night owl 🌙', 'Early bird 🌅'],
    correct: 'Night owl 🌙',
    weight: 10,
  },
  {
    id: 12,
    type: 'personality',
    question: 'Coding style: plan vs jump in?',
    options: ['Jump in ⚡', 'Plan it 🗺️'],
    correct: 'Jump in ⚡',
    weight: 10,
  },
  {
    id: 13,
    type: 'personality',
    question: 'Music vibe?',
    options: ['Melody 🎶', 'Beats 🔊'],
    correct: 'Melody 🎶',
    weight: 10,
  },
  {
    id: 14,
    type: 'personality',
    question: 'Introvert vs extrovert?',
    options: ['Introvert 🌿', 'Extrovert 🎉'],
    correct: 'Introvert 🌿',
    weight: 10,
  },
  {
    id: 15,
    type: 'personality',
    question: 'Travel or stay home?',
    options: ['Stay home 🏠', 'Travel ✈️'],
    correct: 'Stay home 🏠',
    weight: 10,
  },
  {
    id: 16,
    type: 'personality',
    question: 'Risk taker or safe player?',
    options: ['Risk taker 🎲', 'Safe player 🛡️'],
    correct: 'Risk taker 🎲',
    weight: 10,
  },
  {
    id: 17,
    type: 'personality',
    question: 'Movies or series?',
    options: ['Movies 🎬', 'Series 📺'],
    correct: 'Movies 🎬',
    weight: 10,
  },
  {
    id: 18,
    type: 'personality',
    question: 'Spicy vs sweet?',
    options: ['Spicy 🌶️', 'Sweet 🍫'],
    correct: 'Spicy 🌶️',
    weight: 10,
  },
  {
    id: 19,
    type: 'personality',
    question: 'Gym or chill?',
    options: ['Chill 😌', 'Gym 💪'],
    correct: 'Chill 😌',
    weight: 10,
  },
  {
    id: 20,
    type: 'personality',
    question: 'Books or reels?',
    options: ['Reels 📱', 'Books 📚'],
    correct: 'Reels 📱',
    weight: 10,
  },
]

